# Generated by Django 4.2.4 on 2023-08-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_token',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
