# Generated by Django 4.2.4 on 2023-08-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUsers', '0002_userprofile_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft')], default='google', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='access_token',
            field=models.TextField(),
        ),
    ]
